### ISSUE TITLE
Mod paths aren't gettings handled correctly with ModOriginImpl

### ISSUE THREAD

**Issue by QboiDev** [Ultreon/bubble-blaster-2#15]
**To Reproduce**
1. Download [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin).
2. Run the game.

**Logs**
*Not available since logs aren't generated in Packaged mode correctly.*

</details>

**Crash report**
<details>
<summary>Spoiler</summary>

```
>>> C R A S H   R E P O R T <<<
// Uncaught exception

java.lang.UnsupportedOperationException: kind NESTED doesn't have paths
	at net.fabricmc.loader.impl.metadata.ModOriginImpl.getPaths(ModOriginImpl.java:54)
	at com.ultreon.bubbles.render.gui.screen.LoadScreen.run(LoadScreen.java:173)
	at java.base/java.lang.Thread.run(Thread.java:833)

=------------------------------------------------------------------=
System Details: 
   OS: Linux 6.2.0-33-generic
   Memory: 780856168/1551892480

=------------------------------------------------------------------=
```

</details>

**Please complete the following information:**
 - OS: Linux 6.2.0-33-generic (Ubuntu 22.04.3 LTS)
 - Bubble Blaster Version: 0.1.0 (Build 81)

**Additional context**
Might be an issue with the game not handling mod paths correctly in `ModOriginsImpl`

**Additional mods used**
* [Fabric Language Kotlin](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin) (Btw, supported by Bubble Blaster since it doesn't depend on a game, it only needs Fabric)

**Comment by QboiDev** [comment]
Fixed in https://github.com/Ultreon/bubble-blaster-2/commit/e56b1e31d2b16d1868cdda3b6eb8726644d699b7
